In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [6]:
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [8]:
import numpy as np

In [15]:
a = [1, 2, 3, 5, 7, 12]

In [16]:
type(a)

list

In [17]:
a = np.array([1, 2, 3, 5, 7, 12])

In [18]:
type(a)

numpy.ndarray

In [19]:
>>> n = np.array([
...     [1, 2, 3],
...     [4, 5, 6],
...     [7, 8, 9]
... ])
print(n.ndim)

2

In [3]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [7]:
print(len(df))
print(df.shape)
print(df.count)

10000
(10000, 11)
<bound method DataFrame.count of       model_year  origin fuel_type         drivetrain  num_doors  \
0           2006  Europe  Gasoline  Front-wheel drive          4
1           2008  Europe    Diesel  Front-wheel drive          4
2           1996    Asia  Gasoline  Front-wheel drive          5
3           1989  Europe  Gasoline  Front-wheel drive          4
4           1994     USA    Diesel  Front-wheel drive          3
...          ...     ...       ...                ...        ...
9995        2005     USA  Gasoline    All-wheel drive          4
9996        1993    Asia  Gasoline    All-wheel drive          2
9997        2014     USA  Gasoline    All-wheel drive          3
9998        2004     USA    Hybrid   Rear-wheel drive          5
9999        2011     USA    Diesel  Front-wheel drive          4

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                    2180              6       243.0            3870
1                    2390              6       272.0            4210
2                    2320              6       267.0            4240
3                    2130              6       258.0            4490
4                    2580              7       304.0            4510
...                   ...            ...         ...             ...
9995                 2470              6       271.0            4690
9996                 2300              6       244.0            4370
9997                 2480              6       267.0            4590
9998                 2180              6       270.0            4450
9999                 2380              6       295.0            4370

      acceleration  fuel_efficiency_mpg
0              NaN                 31.9
1              NaN                 31.3
2             17.3                 27.5
3             18.7                 28.5
4             17.5                 31.0
...            ...                  ...
9995          18.9                 27.4
9996          19.0                 30.0
9997          18.4                 28.1
9998          20.9                 32.2
9999          17.6                 30.2

[10000 rows x 11 columns]>

In [6]:
print(df['fuel_type'].unique())

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [9]:
q5=df.sort_values(by='fuel_efficiency_mpg', ascending=False).head(3)
print(q5)

      model_year  origin fuel_type         drivetrain  num_doors  \
6354        2022    Asia    Diesel  Front-wheel drive          4
4077        2017    Asia    Hybrid  Front-wheel drive          5
2708        2005  Europe    Diesel  Front-wheel drive          4

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
6354                 1990              6       225.0            3870
4077                 2060              6       196.0            3910
2708                 1890              5       223.0            4040

      acceleration  fuel_efficiency_mpg
6354          17.2                 41.2
4077          19.4                 39.8
2708          18.9                 39.4

In [18]:
q6_1=df['horsepower'].median()
print(q6_1)
hasNA=df['horsepower'].isna().any()
print(hasNA)

252.0
False

In [19]:
q6_2=df['horsepower'].mode()[0]
print(q6_2)

252.0

In [20]:
df['horsepower']=df['horsepower'].fillna(q6_2)
q6_4=df['horsepower'].median()
print(q6_4)

252.0

In [23]:
q7_1_2=df[df['origin']=='Asia'].head(7)
print(q7_1_2)
q7_1_3=q7_1_2[['vehicle_weight', 'model_year']]
print(q7_1_3)

    model_year origin fuel_type         drivetrain  num_doors  \
2         1996   Asia  Gasoline  Front-wheel drive          5
6         1992   Asia  Gasoline  Front-wheel drive          2
8         1997   Asia  Gasoline   Rear-wheel drive          3
10        1978   Asia  Gasoline    All-wheel drive          3
15        2007   Asia    Diesel  Front-wheel drive          4
16        2021   Asia  Gasoline    All-wheel drive          5
22        2019   Asia  Gasoline  Front-wheel drive          5

    engine_displacement  num_cylinders  horsepower  vehicle_weight  \
2                  2320              6       267.0            4240
6                  2270              6       250.0            4310
8                  2330              6       251.0            4230
10                 2410              6       252.0            4420
15                 2170              5       226.0            3950
16                 2280              6       234.0            4750
22                 2350              6       246.0            4450

    acceleration  fuel_efficiency_mpg
2           17.3                 27.5
6           21.7                 26.8
8           19.5                 30.9
10          19.5                 26.8
15          18.0                 35.4
16          20.1                 29.7
22          18.7                 32.7
    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [30]:
import numpy as np
X=q7_1_3.to_numpy()
XTX=X.T @ X
print('top 7 results: ',X)
print('matrix-matrix multiplication: ', XTX)

q7_1_6=np.linalg.inv(XTX)
y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w=q7_1_6 @ X.T @ y
print('w is: ',w)

top 7 results:  [[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]
matrix-matrix multiplication:  [[131950500  60750580]
 [ 60750580  28041424]]
w is:  [0.13644777 0.2327492 ]

In [35]:
print('sum is: ',w[0]+w[1])

sum is:  0.36919696904925486