In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [6]:
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [4]:
import numpy as np
np.random.seed(2)
test=np.random.rand(3)
print(test)

test0=np.random.rand(3)
print(test0)

[0.4359949  0.02592623 0.54966248]
[0.43532239 0.4203678  0.33033482]

In [6]:
test1=np.random.rand(3)
print(test1)

[0.26682728 0.62113383 0.52914209]

In [1]:
import numpy as np

u = np.array([2, 4, 5, 6])  # Shape: (4,)
v = np.array([[1]])         # Shape: (1, 1)

In [2]:
print (u+v)

[[3 5 6 7]]

In [3]:
print (u.shape)
print (v.shape)

(4,)
(1, 1)

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [6]:
df = pd.DataFrame(data, columns=columns)
print (df)

      Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC
2    Lotus     Elise  2010      218.0                 4            MANUAL
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC
4   Nissan  Frontier  2017      261.0                 6            MANUAL

  Vehicle_Style   MSRP
0         sedan   2000
1         Sedan  27150
2   convertible  54990
3       4dr SUV  34450
4        Pickup  32340

In [12]:
df.loc[1]
df.index

RangeIndex(start=0, stop=5, step=1)

In [13]:
df.isna().any()

Make                 False
Model                False
Year                 False
Engine HP             True
Engine Cylinders     False
Transmission Type    False
Vehicle_Style        False
MSRP                 False
dtype: bool

In [17]:

print(df.isna().sum())

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [18]:
df.isna().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [21]:
df[df['Year'] >= 2015 ]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340